### ISSUE TITLE
Option for skip "sample" files.

### ISSUE THREAD

**Issue by zsozso** [byroot/ruby-osdb#22]
Most of the time there is a sample file next to to real movie file. 
The program should skip those or at least needs an option flag for skip.

Example:

* Search subtitles for example.2013.s02e10.720p.bluray.x264-demand
* Sub already there. To override it use --force

* Search subtitles for example.2013.s02e10.720p.bluray.x264-demand.sample
* No sub found

**Comment by byroot** [comment]
You can do it with `find` and `xargs`:

```bash
find . -name *.mp4 | grep -v sample | xargs getsub
```
