### ISSUE TITLE
Language argument defaults to english unless --L is used

### ISSUE THREAD

**Issue by guilsa** [byroot/ruby-osdb#25]
Documentation states -L should be used but the following call defaults to an english subtitle download 

`getsub -L fr .`

whereas --L works:

`getsub --L fr .`

**Comment by byroot** [comment]
From the `-h` summary:

```
    -l, --language LANGUAGE          Sub language ISO 639-2 code like fre or eng. Default: env $LANG     -L, --language-extension         Add the ISO 639-2 in the subtitle's file extension. e.g filename.eng.srt
```

Basically I thin you want `-l` not `-L`

**Comment by guilsa** [comment]
Thanks @byroot, you're correct.
